name: Go
on: 
  push: 
    branches: 
      - "**"
    tags-ignore: 
      - "v*"
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14.2
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Apply GoBin from GOPATH
      shell: bash
      run: echo "::add-path::$(go env GOPATH)/bin"
      
    - name: Build
      run: make all
